site_name: RGBwiki
site_author: Tyler McCann
docs_dir: ./vault # Root Directory (Obsidian Vault)
copyright: Copyright &copy; 2023 (@tylerdotrar)


# Repository
repo_name: tylerdotrar/RGBwiki
repo_url: https://github.com/tylerdotrar/RGBwiki
edit_uri: blob/main/vault/


# Custom Homepage Elements
home_cover_image: attachments/RGBwiki.png
home_tagline: Welcome to RGBwiki
home_description: |
  Explore the entire RGB spectrum and fortify your knowledge in the world of DevOps & digital security.

# Custom Homepage Button(s)
home_button1_name: Red Cell   # Comment this parameter out to remove the button.
home_button1_url: Red Cell/   # This path starts at your root mkdocs directory.
home_button1_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button1_icon: people     # Options: "people", "gear", "image"
home_button1_blurb: Dive into the Red Cell for techniques surrounding Pentesting, Ethical Hacking, and Red Teaming.

home_button2_name: Green Cell # Comment this parameter out to remove the button.
home_button2_url: Green Cell/ # This path starts at your root mkdocs directory.
home_button2_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button2_icon: gear       # Options: "people", "gear", "image"
home_button2_blurb: Navigate through the Green Cell for insights into Infrastructure, DevOps, and IT operations.

home_button3_name: Blue Cell  # Comment this parameter out to remove the button.
home_button3_url: Blue Cell/  # This path starts at your root mkdocs directory.
home_button3_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button3_icon: image      # Options: "people", "gear", "image"
home_button3_blurb: Explore the Blue Cell for Cybersecurity defense and threat analytics.


# Material Configuration
theme:
  name: material
  custom_dir: assets # Contains custom 'home.html' coverpage
  
  features:
    # Page Interaction
    - content.action.edit # View source code on Github
    - content.code.copy   # Codeblocks can be copied to clipboard
    
    # Optimized Navigation
    - navigation.indexes          # Implied section 'index.md' files
    - navigation.tabs             # Static upper section tabs (exist)
    - navigation.tabs.sticky      # Static upper section tabs (stay)
    - navigation.top              # 'Back to top' Button when scrolling up
    - navigation.tracking         # Update URL while scrolling
    - navigation.footer           # Add 'previous' and 'next' buttons in the footer
    - navigation.instant          # Keep navigation from reloading
    - navigation.instant.prefetch # Aid navigation loading times
    - navigation.instant.progress # Display page loading progress-bar
    - toc.follow                  # Update navigation while scrolling
    
    # Do I want this:
    - toc.integrate       # Current document contents built into Navigation
    - navigation.sections # Grouping of directories into sections
    #- navigation.expand  # Auto-expand all directories/sections
    
    # Improve Search Functionality
    - search.highlight
    - search.share
    - search.suggest
    
    
  palette:
    # Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink #teal
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Dark Mode

    # Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink #teal
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to Light Mode


# Extensions
markdown_extensions:
  - footnotes
  - attr_list # File Download Support
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  
  # Mermaid Diagram Support
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  
  # Added for Obsidian callout support
  - nl2br
  - admonition
  - pymdownx.details
  

# Plugins
plugins:
  - search
  - roamlinks # Obsidian Style Image Support ![[<attachment_name>]]
  - callouts
  - mermaid2:
      javascript: js/mermaid.min.js 


# Returning deprecated message
#extra_javascript:
#  - javascripts/mathjax.js
#  - https://polyfill.io/v3/polyfill.min.js?features=es6
#  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-c